---
title: "EDAV"
output: html_document
date: "2025-02-25"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tseries)
```

## R Markdown

```{r summary statistics}

df <- read.csv("C://Users/44758/Downloads/energy_demand_uk.csv")

df$date <- as.Date(df$date)

# Summary statistics for the national demand column
summary(df$national_demand)

mean <- mean(df$national_demand, na.rm = TRUE)
median <- median(df$national_demand, na.rm = TRUE)
sd <- sd(df$national_demand, na.rm = TRUE)
min <- min(df$national_demand, na.rm = TRUE)
max <-max(df$national_demand, na.rm = TRUE)

paste("standard deviation", sd)


```
```{r investigation}
df <- df %>% select(national_demand, date)
print(df)
```
## Including Plots

You can also embed plots, for example:

```{r exploratory plots, echo=FALSE}
# Histogram of the national demand using ggplot2
distribution_plot <- ggplot(df, aes(x = national_demand)) +
  geom_histogram(binwidth = 1000, fill = "blue", color = "black") +
  labs(title = "Histogram of National Demand", x = "National Demand", y = "Frequency")

# Histogram shows a bimodal distribution of the national demand variable potentially at the winter and summer peaks, with winter being the higher peak

# Boxplot
ggplot(df, aes(y = national_demand)) +
  geom_boxplot(fill = "orange") +
  labs(title = "Boxplot of National Demand", y = "National Demand") + 
  theme_minimal()

# Time Series
Time_series_plot <- ggplot(df, aes(x = date, y = national_demand)) +
  geom_line(color="blue") +
  #geom_smooth(method = "glm") +
  labs(title = "National Energy Demand Time Series (2020-2024)", x = "Date", y = "National Energy Demand (MW)") +
  theme_minimal()

ggsave("C:/Users/44758/OneDrive/Desktop/Time_series_plot.png", Time_series_plot)
ggsave("C:/Users/44758/OneDrive/Desktop/distribution_plot.png", distribution_plot)
print(Time_series_plot)
# Clear cyclical element to energy demand caused by a seasonal effect of higher demand of energy in winter

```

```{r Time Series Analysis}
# A time series is stationary if it fulfills the following conditions:
# - The expected value of Y is constant over time
# - the variance of y is finite
# - the covariance of yt and y(t + h) depends only on the value of h = 0,1,2,.. for all t
# 
# Looks broadly stationary but let's inspect further by performing an Augmented Dickey Fuller test
# Perform the Augmented Dickey-Fuller test to check for stationary
adf_test <- adf.test(df$national_demand, alternative = "stationary")
adf_test

# reject the null hypothesis of the ADF test that the time series is stationary so we can assume that the time series is stationary at a 5% significance level.

acf(df$national_demand, main = "Autocorrelation Plot of National Demand")

```

```{r Seasonality Analysis}

df <- read.csv("C://Users/44758/Downloads/energy_demand_uk.csv")
df <- df %>% drop_na()
energy_demand <- df$national_demand

df <- as.ts(energy_demand)

old_par <- par(mfrow = c(2, 2))

plot(energy_demand) # data in time domain

spectrum_result <- spectrum(energy_demand, plot = FALSE)

spectrum(energy_demand, spans = 20)

common_frequency  <- spectrum_result$freq[which.max(spectrum_result$spec)]

common_frequency

paste("Spectral Analysis implies a periodicity of: ", 1/common_frequency)
```

```{r Spectrum Analysis}
